const PRIMARY_TEXT_COLOR = "#302B2D";
const WARNING_COLOR = "#FFC857";
const ERROR_COLOR = "#F93943";
const WHITE_COLOR = "	#FFFFFF";

export {
  PRIMARY_TEXT_COLOR,
  WARNING_COLOR,
  ERROR_COLOR,
  WHITE_COLOR
 };
